version: "3"
services:
  mongo:
    image: mongo:4.2
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./.docker/mongo/:/docker-entrypoint-initdb.d/
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --sql-mode=''
    environment:
      MYSQL_DATABASE: locations
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
      TZ: UTC
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql/:/docker-entrypoint-initdb.d/
